console.log("Hello, World!");
console.log("Hello, Universe!");
console.log("Hello, Multiverse!");
console.log("Hello, Galaxy!");
console.log("Hello, Solar System!");
console.log("Hello, Earth!");
console.log("Hello, Humanity!");
console.log("Hello, Life!");
console.log("this is bad code");
console.log("Hello, Code!");
console.log("Hello, Developer!");